/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Ventanas;

/**
 *
 * @author diego
 */
public class IdentifAcceso extends javax.swing.JFrame {

    /**
     * Creates new form carnetAcceso
     */
    public IdentifAcceso() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipalCarnet = new javax.swing.JPanel();
        lblTituloCarnetAcceso = new javax.swing.JLabel();
        lblApellidosCarnet = new javax.swing.JLabel();
        lblNombreCarnet = new javax.swing.JLabel();
        lblCodEmpCarnet = new javax.swing.JLabel();
        lblAreaCarnet = new javax.swing.JLabel();
        lblPuestoCarnet = new javax.swing.JLabel();
        txtNombresCarnet = new javax.swing.JTextField();
        txtApellidosCarnet = new javax.swing.JTextField();
        txtCodEmpCarnet = new javax.swing.JTextField();
        txAreaCarnet = new javax.swing.JTextField();
        txtPuestoCarnet = new javax.swing.JTextField();
        btnGenerarCarnet = new javax.swing.JButton();
        btnSalirCarnet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTituloCarnetAcceso.setText("CARNET DE ACCESO ");

        lblApellidosCarnet.setText("Apellidos :");

        lblNombreCarnet.setText("Nombres :");

        lblCodEmpCarnet.setText("Codigo de empleado :");

        lblAreaCarnet.setText("Area :");

        lblPuestoCarnet.setText("Puesto :");

        txtCodEmpCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEmpCarnetActionPerformed(evt);
            }
        });

        txAreaCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAreaCarnetActionPerformed(evt);
            }
        });

        btnGenerarCarnet.setText("Generar");

        btnSalirCarnet.setText("Salir");

        javax.swing.GroupLayout pnlPrincipalCarnetLayout = new javax.swing.GroupLayout(pnlPrincipalCarnet);
        pnlPrincipalCarnet.setLayout(pnlPrincipalCarnetLayout);
        pnlPrincipalCarnetLayout.setHorizontalGroup(
            pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloCarnetAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreCarnet)
                            .addComponent(lblApellidosCarnet)
                            .addComponent(lblCodEmpCarnet)
                            .addComponent(lblAreaCarnet)
                            .addComponent(lblPuestoCarnet))
                        .addGap(62, 62, 62)
                        .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombresCarnet)
                            .addComponent(txtApellidosCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txtCodEmpCarnet)
                            .addComponent(txAreaCarnet)
                            .addComponent(txtPuestoCarnet))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalCarnetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnSalirCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        pnlPrincipalCarnetLayout.setVerticalGroup(
            pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                                .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPrincipalCarnetLayout.createSequentialGroup()
                                        .addComponent(lblTituloCarnetAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblNombreCarnet)
                                            .addComponent(txtNombresCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(lblApellidosCarnet))
                                    .addComponent(txtApellidosCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblCodEmpCarnet))
                            .addComponent(txtCodEmpCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAreaCarnet))
                    .addComponent(txAreaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPuestoCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuestoCarnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnlPrincipalCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarCarnet)
                    .addComponent(btnSalirCarnet))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipalCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipalCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txAreaCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAreaCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAreaCarnetActionPerformed

    private void txtCodEmpCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEmpCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEmpCarnetActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerarCarnet;
    public javax.swing.JButton btnSalirCarnet;
    public javax.swing.JLabel lblApellidosCarnet;
    public javax.swing.JLabel lblAreaCarnet;
    public javax.swing.JLabel lblCodEmpCarnet;
    public javax.swing.JLabel lblNombreCarnet;
    public javax.swing.JLabel lblPuestoCarnet;
    public javax.swing.JLabel lblTituloCarnetAcceso;
    public javax.swing.JPanel pnlPrincipalCarnet;
    public javax.swing.JTextField txAreaCarnet;
    public javax.swing.JTextField txtApellidosCarnet;
    public javax.swing.JTextField txtCodEmpCarnet;
    public javax.swing.JTextField txtNombresCarnet;
    public javax.swing.JTextField txtPuestoCarnet;
    // End of variables declaration//GEN-END:variables
}
