/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista.Ventanas;

import Vista.IUControlTiempos;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import Controlador.ControladorValidarInputs;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class VtnEditarTrabajador extends javax.swing.JFrame {
    JFileChooser dlg = new JFileChooser();
    public FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivo de imagen ","png");
    //public FileNameExtensionFilter filtroCarnet= new FileNameExtensionFilter("Documento ","pdf");

    /**
     * Creates new form VtnNuevoTrabajador
     */
    variableStatica ventana = new variableStatica();
    
    //Instanciamos el controlado validar inputs
    
    ControladorValidarInputs validarInputs = new ControladorValidarInputs();
    
    
    
    
    public VtnEditarTrabajador() {
        initComponents();
        setLocationRelativeTo(this);
        //Validamos los inputs
        validarInputs.validarsololetras(txtNom);
        validarInputs.validarsololetras(txtApPa);
        validarInputs.validarsololetras(txtApMa);
        validarInputs.validarsolonumeros(txtTelf);
        validarInputs.limitarcaraceteres(txtTelf, 9);
        validarInputs.validarsolonumeros(txtDNI);
        validarInputs.limitarcaraceteres(txtDNI, 8);
        //Fin de validación
        addWindowListener( new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e ) 
            { 
                ventana.ventanaNuevoTrabajador=false;
                dispose();
            } 
        } 
        );
        this.setResizable(false);
        grupoSexo.add(rbtnHombre);
        grupoSexo.add(rbtnMujer);
        dlg.setCurrentDirectory(new File("C:\\Documents and Settings\\diego\\Mis documentos\\NetBeansProjects\\ProyectoControlTiempos\\ControlDeTiemposv9\\ControlDeTiempos\\CarnetEmpleado\\"));
        txtRutaCarnet.setText("C:\\Documents and Settings\\diego\\Mis documentos\\NetBeansProjects\\ProyectoControlTiempos\\ControlDeTiemposv9\\ControlDeTiempos\\CarnetEmpleado\\");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlDatosPersonales = new javax.swing.JPanel();
        lblApPa = new javax.swing.JLabel();
        lblApMa = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblSex = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblFechNac = new javax.swing.JLabel();
        lblDisRes = new javax.swing.JLabel();
        lblDirec = new javax.swing.JLabel();
        lblTelf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAsig = new javax.swing.JLabel();
        txtApPa = new javax.swing.JTextField();
        txtApMa = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtFechNac = new javax.swing.JTextField();
        txtDirec = new javax.swing.JTextField();
        txtTelf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        cbDsitritoRes = new javax.swing.JComboBox();
        cbAsig = new javax.swing.JComboBox();
        pnlDatosEmpresa = new javax.swing.JPanel();
        lblArea = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblRet = new javax.swing.JLabel();
        cbArea = new javax.swing.JComboBox();
        cbPuesto = new javax.swing.JComboBox();
        cbReten = new javax.swing.JComboBox();
        btnGrabar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlFotoTrabajador = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btnBuscarFoto = new javax.swing.JButton();
        txtRutaFoto = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnGuardarCarnet = new javax.swing.JButton();
        txtRutaCarnet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Editar Empleado");

        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Personales"));

        lblApPa.setText("Apellido Paterno :");

        lblApMa.setText("Apellido Materno :");

        lblNom.setText("Nombres :");

        lblSex.setText("Sexo :");

        lblDni.setText("DNI :");

        lblFechNac.setText("Fecha de nacimiento :");

        lblDisRes.setText("Distrito de residencia :");

        lblDirec.setText("Dirección :");

        lblTelf.setText("Celular :");

        lblEmail.setText("E-mail :");

        lblAsig.setText("Asignación familiar :");

        txtApMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApMaActionPerformed(evt);
            }
        });

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        rbtnHombre.setText("Masculino");

        rbtnMujer.setText("Femenino");

        cbDsitritoRes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un opción", "Cercado de Lima", "Ate", "Barranci", "Breña", "Comas", "Chorrillos", "El Agustino", "Jesús MaríaLa Molina", "La Victoria", "Lince", "Magdalena del Mar", "Miraflores", "Pueblo Libre", "Puente Piedra", "Rimac", "San Isidro", "Independencia", "San Juan de Miraflores", "San Luis", "San Martin de Porres", "San Miguel", "Santiago de Surco", "Surquillo", "Villa María del Triunfo", "San Juan de Lurigancho", "Santa Rosa", "Los Olivos", "San Borja", "Villa El Savador", "Santa Anita" }));

        cbAsig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción", "Si", "No" }));

        javax.swing.GroupLayout pnlDatosPersonalesLayout = new javax.swing.GroupLayout(pnlDatosPersonales);
        pnlDatosPersonales.setLayout(pnlDatosPersonalesLayout);
        pnlDatosPersonalesLayout.setHorizontalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApPa)
                    .addComponent(lblNom)
                    .addComponent(lblDni)
                    .addComponent(lblDisRes)
                    .addComponent(lblTelf)
                    .addComponent(lblAsig))
                .addGap(41, 41, 41)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNom)
                    .addComponent(txtDNI)
                    .addComponent(txtApPa)
                    .addComponent(txtTelf)
                    .addComponent(cbDsitritoRes, 0, 147, Short.MAX_VALUE)
                    .addComponent(cbAsig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApMa)
                    .addComponent(lblSex)
                    .addComponent(lblFechNac)
                    .addComponent(lblDirec)
                    .addComponent(lblEmail))
                .addGap(23, 23, 23)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDirec, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechNac, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(rbtnHombre)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnMujer)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEmail))
                .addGap(28, 28, 28))
        );
        pnlDatosPersonalesLayout.setVerticalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApPa)
                    .addComponent(txtApPa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApMa)
                    .addComponent(txtApMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSex)
                    .addComponent(rbtnHombre)
                    .addComponent(rbtnMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechNac)
                    .addComponent(txtFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisRes)
                    .addComponent(lblDirec)
                    .addComponent(txtDirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDsitritoRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelf)
                    .addComponent(txtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsig)
                    .addComponent(cbAsig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnlDatosEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Empresa"));

        lblArea.setText("Area :");

        lblPuesto.setText("Puesto :");

        lblRet.setText("Retención :");

        cbArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbAreaMousePressed(evt);
            }
        });
        cbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAreaActionPerformed(evt);
            }
        });

        cbReten.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cbReten.setToolTipText("");

        javax.swing.GroupLayout pnlDatosEmpresaLayout = new javax.swing.GroupLayout(pnlDatosEmpresa);
        pnlDatosEmpresa.setLayout(pnlDatosEmpresaLayout);
        pnlDatosEmpresaLayout.setHorizontalGroup(
            pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArea)
                    .addComponent(lblRet))
                .addGap(96, 96, 96)
                .addGroup(pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbArea, 0, 147, Short.MAX_VALUE)
                    .addComponent(cbReten, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52)
                .addComponent(lblPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(cbPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlDatosEmpresaLayout.setVerticalGroup(
            pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(lblPuesto)
                    .addComponent(cbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRet)
                    .addComponent(cbReten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        pnlFotoTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Foto"));

        lblFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscarFoto.setText("Buscar Foto");
        btnBuscarFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFotoActionPerformed(evt);
            }
        });

        txtRutaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFotoTrabajadorLayout = new javax.swing.GroupLayout(pnlFotoTrabajador);
        pnlFotoTrabajador.setLayout(pnlFotoTrabajadorLayout);
        pnlFotoTrabajadorLayout.setHorizontalGroup(
            pnlFotoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoTrabajadorLayout.createSequentialGroup()
                .addGroup(pnlFotoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFotoTrabajadorLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(pnlFotoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRutaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFotoTrabajadorLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnBuscarFoto)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlFotoTrabajadorLayout.setVerticalGroup(
            pnlFotoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFotoTrabajadorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnBuscarFoto)
                .addGap(39, 39, 39)
                .addComponent(txtRutaFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("EDITAR TRABAJADOR");

        btnGuardarCarnet.setText("Guardar Carnet");
        btnGuardarCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCarnetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlFotoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                            .addComponent(btnGuardarCarnet)
                            .addGap(18, 18, 18)
                            .addComponent(txtRutaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31))
                        .addComponent(pnlDatosEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(pnlDatosEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarCarnet)
                            .addComponent(txtRutaCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(pnlFotoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApMaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      
        ventana.ventanaNuevoTrabajador=false;
        dispose();
        
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnBuscarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFotoActionPerformed
        JFileChooser selector = new JFileChooser(); 
        selector.setFileFilter(filtro);
        int opcion=selector.showOpenDialog(this);
        if(opcion==JFileChooser.APPROVE_OPTION) 
        {
            String nombreArchivo= selector.getSelectedFile().getPath();
            String ruta=selector.getSelectedFile().toString();
            lblFoto.setIcon(new ImageIcon(nombreArchivo));
            
            ImageIcon icono= new ImageIcon(nombreArchivo);
            Image imagen = icono.getImage();
            Image nuevaImagen = imagen.getScaledInstance(164, 210, java.awt.Image.SCALE_SMOOTH);
            ImageIcon nuevoIcono=new ImageIcon(nuevaImagen);
            lblFoto.setIcon(nuevoIcono);
            txtRutaFoto.setText(nombreArchivo);
            
        }
    }//GEN-LAST:event_btnBuscarFotoActionPerformed

    private void txtRutaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaFotoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
if(!validarInputs.validaremail(txtEmail)) {JOptionPane.showMessageDialog(this, "Email incorrecto","Error de formato Email",JOptionPane.ERROR_MESSAGE);
txtEmail.selectAll();
txtEmail.requestFocus();}
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnGuardarCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCarnetActionPerformed

         dlg.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = dlg.showSaveDialog(this);
        
        if(option==JFileChooser.APPROVE_OPTION)
        {
            File f=dlg.getSelectedFile();
            txtRutaCarnet.setText(f.toString());
            
            System.out.println(txtRutaCarnet.getText());
        }
    }//GEN-LAST:event_btnGuardarCarnetActionPerformed

    private void cbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAreaActionPerformed

    private void cbAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbAreaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAreaMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarFoto;
    public javax.swing.JButton btnGrabar;
    public javax.swing.JButton btnGuardarCarnet;
    public javax.swing.JButton btnSalir;
    public javax.swing.JComboBox cbArea;
    public javax.swing.JComboBox cbAsig;
    public javax.swing.JComboBox cbDsitritoRes;
    public javax.swing.JComboBox cbPuesto;
    public javax.swing.JComboBox cbReten;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel lblApMa;
    private javax.swing.JLabel lblApPa;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblAsig;
    private javax.swing.JLabel lblDirec;
    private javax.swing.JLabel lblDisRes;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechNac;
    public javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblRet;
    private javax.swing.JLabel lblSex;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlDatosEmpresa;
    private javax.swing.JPanel pnlDatosPersonales;
    public javax.swing.JPanel pnlFotoTrabajador;
    public javax.swing.JPanel pnlPrincipal;
    public javax.swing.JRadioButton rbtnHombre;
    public javax.swing.JRadioButton rbtnMujer;
    public javax.swing.JTextField txtApMa;
    public javax.swing.JTextField txtApPa;
    public javax.swing.JTextField txtDNI;
    public javax.swing.JTextField txtDirec;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtFechNac;
    public javax.swing.JTextField txtNom;
    public javax.swing.JTextField txtRutaCarnet;
    public javax.swing.JTextField txtRutaFoto;
    public javax.swing.JTextField txtTelf;
    // End of variables declaration//GEN-END:variables
}
